FROM openjdk:18-jdk-alpine3.14
MAINTAINER cecar.edu.co
COPY ./war/CalculateEstaditicasConcurrenciaServicio-1.0.war /usr/app/
COPY ./datasets/* /usr/app/datasets/
WORKDIR /usr/app
ENTRYPOINT ["java","-jar","CalculateEstaditicasConcurrenciaServicio-1.0.war"]
