version: '3.9'
services:
  appapiga4:
    container_name: CalculateSaleService
    build: .
    restart: always
    ports:
        - 8080:8080
    environment:
      - SERVER.PORT=8080
      - SPRING.APPLICATION.NAME=CalculateEstaditicasConcurrenciaServicio
      - SPRING.PATH=datasets/
      - SPRING.FILEHASHEADER=true
 